import type { PageTimers, GameConfig } from "@tiktok/types";

export const DEFAULT_TIMERS: PageTimers = {
  selectGameMs: 45_000,
  rulesMs: 15_000,
  roundSummaryMs: 12_000,
  scoreboardMs: 20_000,
  supportMs: 15_000,
};

// Galatasaray/Futbol LIVE modülleri.
// ID'leri stabil tutuyoruz; seçim geçmişi ve skor sistemi bunlara bağlanabilir.
export const GAMES: GameConfig[] = [
  {
    id: "gsQuiz",
    name: "Galatasaray Quiz",
    category: "quiz",
    categoryDescription: "Bilgi Yarışması",
    description: "Galatasaray tarihi, oyuncular, sezonlar ve futbol bilgisi üzerine hızlı sorular.",
    defaultRounds: 8,
    defaultRoundDurationMs: 25_000,
    gameImage: "",
    rules: ["Ekrandaki soruyu oku.", "Cevabını yorumlara 1, 2 veya 3 olarak yaz.", "Süre bitince doğru cevap ve sonuç gösterilir.", "Doğru cevaplar puan tablosuna eklenebilir."],
    nameEn: "Galatasaray Quiz",
    categoryDescriptionEn: "Trivia",
    descriptionEn: "Fast questions about Galatasaray history, players, seasons and football.",
    rulesEn: ["Read the question", "Answer with 1, 2 or 3", "The answer is revealed when time expires", "Correct answers can earn points"],
  },
  {
    id: "playerGuess",
    name: "Futbolcuyu Tahmin Et",
    category: "playerGuess",
    categoryDescription: "Oyuncu Tahmini",
    description: "Kariyer, forma numarası, mevki veya sezon ipuçlarından futbolcuyu bul.",
    defaultRounds: 8,
    defaultRoundDurationMs: 30_000,
    gameImage: "",
    rules: ["İpuçları sırayla açılır.", "Oyuncunun adını yoruma yaz.", "Erken doğru cevap daha yüksek puan verebilir.", "Süre sonunda oyuncu açıklanır."],
    nameEn: "Guess the Player",
    categoryDescriptionEn: "Player Guess",
    descriptionEn: "Guess the footballer from career, number, position or season clues.",
    rulesEn: ["Clues appear progressively", "Type the player name", "Earlier correct answers may score more", "The player is revealed at timeout"],
  },
  {
    id: "playerVs",
    name: "Oyuncu Kapışması",
    category: "versus",
    categoryDescription: "A/B Oylama",
    description: "İki oyuncudan hangisini seçtiğini A veya B yazarak belirle.",
    defaultRounds: 10,
    defaultRoundDurationMs: 25_000,
    gameImage: "",
    rules: ["Sol oyuncu için A, sağ oyuncu için B yaz.", "Her turda oylar canlı sayılır.", "Süre sonunda çoğunluğun seçimi gösterilir.", "Yakın zamanda kullanılan eşleşmeler tekrar edilmez."],
    nameEn: "Player Versus",
    categoryDescriptionEn: "A/B Vote",
    descriptionEn: "Choose between two players by typing A or B.",
    rulesEn: ["Type A for the left player or B for the right player", "Votes are counted live", "The majority choice is shown at timeout", "Recent matchups are avoided"],
  },
  {
    id: "historyQuiz",
    name: "Tarihten Bir Soru",
    category: "history",
    categoryDescription: "Galatasaray Tarihi",
    description: "Kupalar, unutulmaz maçlar, teknik direktörler ve geçmiş sezonlar üzerine sorular.",
    defaultRounds: 8,
    defaultRoundDurationMs: 30_000,
    gameImage: "",
    rules: ["Soruyu ve seçenekleri oku.", "1, 2 veya 3 yazarak cevap ver.", "Süre bitiminde kısa açıklamayla doğru cevap gösterilir.", "Aynı soru kısa sürede tekrar gösterilmez."],
    nameEn: "History Quiz",
    categoryDescriptionEn: "Galatasaray History",
    descriptionEn: "Questions about trophies, memorable matches, managers and past seasons.",
    rulesEn: ["Read the question", "Answer 1, 2 or 3", "The correct answer is revealed with a short explanation", "Recent questions are not repeated"],
  },
  {
    id: "lineupBuilder",
    name: "İlk 11'i Kur",
    category: "lineup",
    categoryDescription: "Kadro Oyunu",
    description: "Pozisyon pozisyon seçim yaparak chat ile ortak bir ilk 11 oluştur.",
    defaultRounds: 11,
    defaultRoundDurationMs: 30_000,
    gameImage: "",
    rules: ["Her turda bir pozisyon için adaylar gösterilir.", "A/B/C seçeneklerinden birini yorumlara yaz.", "En çok oy alan oyuncu kadroya eklenir.", "11 pozisyon tamamlandığında oluşturulan kadro gösterilir."],
    nameEn: "Build the XI",
    categoryDescriptionEn: "Lineup Game",
    descriptionEn: "Build a starting eleven together with chat, one position at a time.",
    rulesEn: ["Candidates are shown for each position", "Vote A/B/C", "The most-voted player joins the XI", "The final lineup is shown after all positions"],
  },
  {
    id: "formationPoll",
    name: "Taktik ve Formasyon Oylaması",
    category: "poll",
    categoryDescription: "Taktik Oylama",
    description: "4-3-3, 4-2-3-1 ve benzeri seçenekler arasında chat karar verir.",
    defaultRounds: 6,
    defaultRoundDurationMs: 25_000,
    gameImage: "",
    rules: ["Ekrandaki taktik senaryosunu oku.", "Seçeneklerden birini yorumlara yaz.", "Oylar gerçek zamanlı sayılır.", "Tur sonunda tercih dağılımı gösterilir."],
    nameEn: "Formation Poll",
    categoryDescriptionEn: "Tactical Poll",
    descriptionEn: "Chat decides between formations and tactical approaches.",
    rulesEn: ["Read the tactical scenario", "Vote for an option", "Votes are counted live", "Results are displayed at the end"],
  },
  {
    id: "higherLower",
    name: "Daha Fazla mı Daha Az mı?",
    category: "stats",
    categoryDescription: "İstatistik Oyunu",
    description: "İki oyuncu veya sezon arasındaki gol, maç, asist gibi istatistikleri karşılaştır.",
    defaultRounds: 10,
    defaultRoundDurationMs: 20_000,
    gameImage: "",
    rules: ["Ekrandaki istatistik kategorisini kontrol et.", "A veya B yazarak daha yüksek değere sahip seçeneği tahmin et.", "Süre bitince gerçek değerler açıklanır.", "Kaynağı doğrulanmamış güncel veri kullanılmaz."],
    nameEn: "Higher or Lower",
    categoryDescriptionEn: "Stats Game",
    descriptionEn: "Compare goals, appearances, assists and other statistics.",
    rulesEn: ["Check the statistic category", "Type A or B for the higher value", "Actual values are revealed", "Unverified current data is not used"],
  },
  {
    id: "ranking",
    name: "Chat Sıralaması",
    category: "ranking",
    categoryDescription: "Sıralama Oyunu",
    description: "Oyuncuları, sezonları veya anları chat oylarıyla sıralamaya çalış.",
    defaultRounds: 5,
    defaultRoundDurationMs: 35_000,
    gameImage: "",
    rules: ["Ekrandaki adaylar arasında seçim yap.", "Yorumlarla sıradaki pozisyonu belirle.", "Her tur sonunda sıralama güncellenir.", "Finalde chat'in oluşturduğu liste gösterilir."],
    nameEn: "Chat Ranking",
    categoryDescriptionEn: "Ranking Game",
    descriptionEn: "Rank players, seasons or moments using chat votes.",
    rulesEn: ["Choose between the candidates", "Chat determines the next rank", "The ranking updates every round", "The final community ranking is displayed"],
  },
  {
    id: "scorePrediction",
    name: "Skor Tahmini",
    category: "prediction",
    categoryDescription: "Tahmin Oyunu",
    description: "Yaklaşan maçlar veya kurgusal senaryolar için skor tahmini yap.",
    defaultRounds: 5,
    defaultRoundDurationMs: 35_000,
    gameImage: "",
    rules: ["Ekrandaki maçı veya senaryoyu incele.", "Skor tahminini 2-1, 1-0 gibi yaz.", "En popüler tahminler ekranda gösterilir.", "Gerçek maç bilgisi kullanılıyorsa veri tarihi ayrıca tutulur."],
    nameEn: "Score Prediction",
    categoryDescriptionEn: "Prediction Game",
    descriptionEn: "Predict scores for upcoming matches or fictional scenarios.",
    rulesEn: ["Review the match or scenario", "Type a score such as 2-1", "Popular predictions are displayed", "Real match data includes a verification date"],
  },
];
