import type { PageTimers, GameConfig } from "@tiktok/types";

export const DEFAULT_TIMERS: PageTimers = {
  selectGameMs: 3 * 60_000,
  rulesMs: 60_000,
  roundSummaryMs: 30_000,
  scoreboardMs: 60_000,
  supportMs: 60_000,
};

export const GAMES: GameConfig[] = [
  {
    id: "guessWordTH",
    name: "ทายคำภาษาไทย",
    category: "guessWord",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "guessWordEN",
    name: "ทายคำภาษาอังกฤษ",
    category: "guessWord",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาอังกฤษให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ภาษาอังกฤษให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "guessFlag",
    name: "ทายภาพธงชาติ",
    category: "guessPicture",
    categoryDescription: "ทายภาพ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีภาพธงชาติให้ทายทั้งหมด 10 ภาพ",
      "ผู้เล่นจะต้องทายชื่อประเทศของธงชาติแต่ละภาพให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "guessMottoTH",
    name: "ทายคำขวัญจังหวัด",
    category: "guessWord",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "wordleTH",
    name: "เกมเวิร์ดเดิลภาษาไทย",
    category: "guessWord",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "wordleEN",
    name: "เกมเวิร์ดเดิลภาษาอังกฤษ",
    category: "wordle",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "Guess the hidden English word in 6 tries.",
      "Each guess must be a valid 5-letter English word.",
      "After each guess, the color of the tiles will change to show how close your guess was to the word.",
    ],
  },
  {
    id: "guessWordTH",
    name: "ทายคำภาษาไทย",
    category: "guessWord",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "contextoTH",
    name: "เกมคอนเท็กโตภาษาไทย",
    category: "contexto",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "davinciTH",
    name: "เกมดาวินชีภาษาไทย",
    category: "davinci",
    categoryDescription: "ทายคำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
  {
    id: "memoryTest",
    name: "ทดสอบความจำ",
    category: "memory",
    categoryDescription: "ความจำ",
    description: "",
    defaultRounds: 10,
    defaultRoundDurationMs: 40_000,
    gameImage: "https://cdn-icons-png.flaticon.com/512/5087/5087579.png",
    rules: [
      "เกมนี้จะมีคำศัพท์ภาษาไทยให้ทายทั้งหมด 10 คำ",
      "ผู้เล่นจะต้องทายคำศัพท์ให้ถูกต้องภายในเวลาที่กำหนด",
    ],
  },
];
